export const PRODUCTS = {
    ADD_PRODUCT : 'ADD_PRODUCT',
    ADD_PRODUCT_SUCCESS : 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_ERROR : 'ADD_PRODUCT_ERROR',
    ADD_FIRST_PRODUCT : 'ADD_FIRST_PRODUCT',
    LAST_PRODUCT_ADD: 'LAST_PRODUCT_ADD'
}

export const LANGUAGE = {
    CHANGE_TO_SPANISH: 'CHANGE_TO_SPANISH',
    CHANGE_TO_ENGLISH: 'CHANGE_TO_ENGLISH'
}